"""Adversarial and Edge Case Test Suite for SafeLane v2 Auth & GitHub Endpoints.

Empirical verification suite created by Challenger 2:
1. PKCE code_verifier tampering and OAuth state mismatch / replay attacks.
2. Missing GitHub token in DB, null token, and Fernet decryption failure simulation.
3. GitHub API error handling (403 rate limit / revoked token, 500 upstream server error, empty repos, multi-page pagination, 500-repo cap).
4. Header vs Cookie auth precedence, invalid cookie handling, and JWT forgery/tampering/expiry.
5. Error status codes, PAT feature-gating security, and sensitive credential leakage prevention.
"""
import os
import urllib.parse
import pytest
from unittest.mock import patch, AsyncMock, MagicMock
from fastapi import FastAPI
from fastapi.testclient import TestClient
from cryptography.fernet import Fernet, InvalidToken
import jwt
from datetime import datetime, timedelta, timezone

# Ensure required environment variables
os.environ.setdefault("JWT_SECRET", "adversarial-jwt-secret-challenger2-98765")
os.environ.setdefault("ENCRYPTION_KEY", Fernet.generate_key().decode())
os.environ.setdefault("GITHUB_CLIENT_ID", "adv_github_client_id")
os.environ.setdefault("GITHUB_CLIENT_SECRET", "adv_github_client_secret")
os.environ.setdefault("FRONTEND_URL", "http://localhost:5173")

from platform_app.server.services.auth_service import (
    create_jwt,
    verify_jwt,
    encrypt_token,
    decrypt_token,
    reset_singletons,
)
from platform_app.server.routers.auth import (
    router as auth_router,
    SESSION_COOKIE_NAME,
    _oauth_states,
    _oauth_verifiers,
    _generate_pkce_pair,
)
from platform_app.server.routers.github_setup import (
    router as github_router,
    _get_user_token,
)
from platform_app.server.services.github_service import (
    exchange_code_for_token,
    get_github_user,
    list_user_repos,
)
from platform_app.server.services.db import User


@pytest.fixture(autouse=True)
def setup_adversarial_env(monkeypatch):
    """Clean cryptographic state and memory caches before and after each test."""
    monkeypatch.setenv("JWT_SECRET", "adversarial-jwt-secret-challenger2-98765")
    key = Fernet.generate_key().decode()
    monkeypatch.setenv("ENCRYPTION_KEY", key)
    monkeypatch.setenv("GITHUB_CLIENT_ID", "adv_github_client_id")
    monkeypatch.setenv("GITHUB_CLIENT_SECRET", "adv_github_client_secret")
    monkeypatch.setenv("FRONTEND_URL", "http://localhost:5173")
    monkeypatch.setenv("COOKIE_SECURE", "false")
    monkeypatch.delenv("PAT_ENDPOINT_ENABLED", raising=False)
    reset_singletons()
    _oauth_states.clear()
    _oauth_verifiers.clear()
    yield
    reset_singletons()
    _oauth_states.clear()
    _oauth_verifiers.clear()


@pytest.fixture
def app():
    """Create FastAPI application with auth and github routers."""
    test_app = FastAPI(title="SafeLane Adversarial Test App")
    test_app.include_router(auth_router, prefix="/api/auth")
    test_app.include_router(github_router, prefix="/api/github")
    return test_app


@pytest.fixture
def client(app):
    """Create TestClient."""
    return TestClient(app)


# ==============================================================================
# 1. PKCE CODE_VERIFIER TAMPERING & OAUTH STATE MISMATCH / REPLAY
# ==============================================================================

@pytest.mark.unit
def test_oauth_callback_state_tampering_unregistered_state(client):
    """Adversary provides a forged/tampered state parameter not generated by the server.
    Expected: HTTP 400 Bad Request with detail 'Invalid OAuth state parameter'."""
    response = client.get(
        "/api/auth/github/callback?code=mock_code&state=adversary_tampered_state_123",
        follow_redirects=False,
    )
    assert response.status_code == 400
    assert response.json()["detail"] == "Invalid OAuth state parameter"


@pytest.mark.unit
def test_oauth_callback_state_replay_attack(client):
    """Adversary attempts to replay a valid OAuth state that has already been consumed.
    Expected: First callback succeeds, second callback fails with HTTP 400 Bad Request."""
    # 1. Initiate login
    login_resp = client.get("/api/auth/github/login", follow_redirects=False)
    assert login_resp.status_code == 307
    state = list(_oauth_states)[0]
    assert state in _oauth_verifiers

    mock_gh_user = {"login": "attacker_or_user", "id": 112233}
    with patch("platform_app.server.routers.auth.exchange_code_for_token", new_callable=AsyncMock) as mock_exchange, \
         patch("platform_app.server.routers.auth.get_github_user", new_callable=AsyncMock) as mock_get_user, \
         patch("platform_app.server.routers.auth.upsert_user", new_callable=AsyncMock) as mock_upsert:

        mock_exchange.return_value = "gho_token_valid_1"
        mock_get_user.return_value = mock_gh_user
        mock_upsert.return_value = None

        # First callback consumes the state
        first_resp = client.get(
            f"/api/auth/github/callback?code=legit_code&state={state}",
            follow_redirects=False,
        )
        assert first_resp.status_code == 307
        assert SESSION_COOKIE_NAME in first_resp.cookies

        # Verify state and verifier were consumed and cleared
        assert state not in _oauth_states
        assert state not in _oauth_verifiers

        # Second callback with the same state must be rejected (replay protection)
        replay_resp = client.get(
            f"/api/auth/github/callback?code=legit_code&state={state}",
            follow_redirects=False,
        )
        assert replay_resp.status_code == 400
        assert replay_resp.json()["detail"] == "Invalid OAuth state parameter"


@pytest.mark.unit
def test_oauth_callback_missing_query_parameters(client):
    """Callback invoked with missing state or code query params.
    Expected: HTTP 422 Unprocessable Entity."""
    # Missing state
    resp1 = client.get("/api/auth/github/callback?code=some_code")
    assert resp1.status_code == 422

    # Missing code
    resp2 = client.get("/api/auth/github/callback?state=some_state")
    assert resp2.status_code == 422

    # Missing both
    resp3 = client.get("/api/auth/github/callback")
    assert resp3.status_code == 422


@pytest.mark.unit
async def test_pkce_verifier_passed_to_github_token_exchange():
    """Verify that the PKCE code_verifier generated at login is sent in payload during token exchange."""
    verifier, challenge = _generate_pkce_pair()
    assert len(verifier) >= 43
    assert len(challenge) > 0

    mock_response = MagicMock()
    mock_response.status_code = 200
    mock_response.json.return_value = {"access_token": "gho_pkce_token_success"}

    with patch("httpx.AsyncClient.post", new_callable=AsyncMock) as mock_post:
        mock_post.return_value = mock_response

        token = await exchange_code_for_token("my_oauth_code", code_verifier=verifier)
        assert token == "gho_pkce_token_success"

        mock_post.assert_called_once()
        _, kwargs = mock_post.call_args
        sent_payload = kwargs.get("json", {})
        assert sent_payload.get("code") == "my_oauth_code"
        assert sent_payload.get("code_verifier") == verifier


@pytest.mark.unit
def test_oauth_callback_upstream_github_exchange_failure(client):
    """When GitHub rejects authorization code (e.g. bad_verification_code), callback catches ValueError
    and gracefully redirects user to frontend with error query parameter."""
    login_resp = client.get("/api/auth/github/login", follow_redirects=False)
    state = list(_oauth_states)[0]

    with patch("platform_app.server.routers.auth.exchange_code_for_token", new_callable=AsyncMock) as mock_exchange:
        mock_exchange.side_effect = ValueError("GitHub OAuth error: The code has expired")

        callback_resp = client.get(
            f"/api/auth/github/callback?code=expired_code&state={state}",
            follow_redirects=False,
        )
        assert callback_resp.status_code == 307
        location = callback_resp.headers["location"]
        unquoted_location = urllib.parse.unquote(location)
        assert "http://localhost:5173/auth/callback?error=" in location
        assert "GitHub OAuth error: The code has expired" in unquoted_location


# ==============================================================================
# 2. MISSING GITHUB TOKEN IN DB & DECRYPTION FAILURE SIMULATION
# ==============================================================================

@pytest.mark.unit
def test_user_repos_user_not_in_db_returns_401(client):
    """User has a valid session JWT, but their user record does not exist in DB (e.g. deleted user).
    Expected: HTTP 401 Unauthorized with detail 'No GitHub token stored. Please re-authenticate.'"""
    session_jwt = create_jwt({"github_username": "ghost_user", "github_id": 999999})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    with patch("platform_app.server.routers.github_setup.get_user_by_github_id", new_callable=AsyncMock) as mock_get_user:
        mock_get_user.return_value = None

        response = client.get("/api/github/user-repos")
        assert response.status_code == 401
        assert "No GitHub token stored" in response.json()["detail"]


@pytest.mark.unit
def test_user_repos_null_encrypted_token_in_db_returns_401(client):
    """User exists in DB, but encrypted_token column is NULL.
    Expected: HTTP 401 Unauthorized with detail 'No GitHub token stored. Please re-authenticate.'"""
    session_jwt = create_jwt({"github_username": "tokenless_user", "github_id": 888888})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    mock_db_user = MagicMock(spec=User)
    mock_db_user.github_id = 888888
    mock_db_user.github_username = "tokenless_user"
    mock_db_user.encrypted_token = None

    with patch("platform_app.server.routers.github_setup.get_user_by_github_id", new_callable=AsyncMock) as mock_get_user:
        mock_get_user.return_value = mock_db_user

        response = client.get("/api/github/user-repos")
        assert response.status_code == 401
        assert "No GitHub token stored" in response.json()["detail"]


@pytest.mark.unit
def test_user_repos_token_decryption_failure(client):
    """Simulate encrypted_token corruption or ENCRYPTION_KEY rotation mismatch.
    Expected: decrypt_token raises InvalidToken when decryption fails with mismatched key."""
    session_jwt = create_jwt({"github_username": "corrupt_token_user", "github_id": 777777})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    mock_db_user = MagicMock(spec=User)
    mock_db_user.github_id = 777777
    mock_db_user.github_username = "corrupt_token_user"
    # Token encrypted with an old/different Fernet key
    other_key = Fernet.generate_key()
    mock_db_user.encrypted_token = Fernet(other_key).encrypt(b"gho_secret").decode()

    with patch("platform_app.server.routers.github_setup.get_user_by_github_id", new_callable=AsyncMock) as mock_get_user:
        mock_get_user.return_value = mock_db_user

        with pytest.raises(InvalidToken):
            client.get("/api/github/user-repos")


# ==============================================================================
# 3. GITHUB API ERROR HANDLING (403, 500, EMPTY REPOS, PAGINATION)
# ==============================================================================

@pytest.mark.unit
def test_user_repos_github_403_rate_limit_handled(client):
    """When GitHub API returns 403 (rate limit or forbidden), endpoint converts to 401 with re-auth prompt."""
    session_jwt = create_jwt({"github_username": "rate_limited_user", "github_id": 666666})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    with patch("platform_app.server.routers.github_setup._get_user_token", new_callable=AsyncMock) as mock_get_token, \
         patch("httpx.AsyncClient.get", new_callable=AsyncMock) as mock_http_get:

        mock_get_token.return_value = "gho_valid_user_token"

        mock_response = MagicMock()
        mock_response.status_code = 403
        mock_http_get.return_value = mock_response

        response = client.get("/api/github/user-repos")
        assert response.status_code == 401
        assert "Please re-authenticate" in response.json()["detail"]


@pytest.mark.unit
def test_user_repos_github_500_upstream_error_handled(client):
    """When GitHub API returns 500/502/503 upstream error, endpoint returns 400 Bad Request."""
    session_jwt = create_jwt({"github_username": "user_upstream_error", "github_id": 555555})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    with patch("platform_app.server.routers.github_setup._get_user_token", new_callable=AsyncMock) as mock_get_token, \
         patch("httpx.AsyncClient.get", new_callable=AsyncMock) as mock_http_get:

        mock_get_token.return_value = "gho_valid_user_token"

        mock_response = MagicMock()
        mock_response.status_code = 500
        mock_http_get.return_value = mock_response

        response = client.get("/api/github/user-repos")
        assert response.status_code == 400
        assert "Failed to fetch repositories: 500" in response.json()["detail"]


@pytest.mark.unit
def test_user_repos_empty_repository_list(client):
    """When user has 0 repositories on GitHub, endpoint returns 200 OK with empty list []."""
    session_jwt = create_jwt({"github_username": "zero_repos_user", "github_id": 444444})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    with patch("platform_app.server.routers.github_setup._get_user_token", new_callable=AsyncMock) as mock_get_token, \
         patch("httpx.AsyncClient.get", new_callable=AsyncMock) as mock_http_get:

        mock_get_token.return_value = "gho_valid_user_token"

        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = []
        mock_http_get.return_value = mock_response

        response = client.get("/api/github/user-repos")
        assert response.status_code == 200
        assert response.json() == []


@pytest.mark.unit
def test_user_repos_multi_page_pagination(client):
    """When user has multiple pages of repositories, endpoint paginates and aggregates all of them."""
    session_jwt = create_jwt({"github_username": "prolific_coder", "github_id": 333333})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    # Page 1: 2 repos, Page 2: 1 repo, Page 3: [] (end)
    page1 = [
        {"name": f"repo-{i}", "full_name": f"prolific_coder/repo-{i}", "owner": {"login": "prolific_coder"}, "private": False, "description": f"Repo {i}", "language": "Python", "updated_at": "2026-09-01", "default_branch": "main"}
        for i in range(1, 3)
    ]
    page2 = [
        {"name": "repo-3", "full_name": "prolific_coder/repo-3", "owner": {"login": "prolific_coder"}, "private": True, "description": "Repo 3", "language": "Rust", "updated_at": "2026-09-02", "default_branch": "main"}
    ]
    page3 = []

    with patch("platform_app.server.routers.github_setup._get_user_token", new_callable=AsyncMock) as mock_get_token, \
         patch("httpx.AsyncClient.get", new_callable=AsyncMock) as mock_http_get:

        mock_get_token.return_value = "gho_valid_user_token"

        resp1, resp2, resp3 = MagicMock(), MagicMock(), MagicMock()
        resp1.status_code, resp1.json.return_value = 200, page1
        resp2.status_code, resp2.json.return_value = 200, page2
        resp3.status_code, resp3.json.return_value = 200, page3

        mock_http_get.side_effect = [resp1, resp2, resp3]

        response = client.get("/api/github/user-repos")
        assert response.status_code == 200
        data = response.json()
        assert len(data) == 3
        assert [r["name"] for r in data] == ["repo-1", "repo-2", "repo-3"]


@pytest.mark.unit
def test_user_repos_pagination_caps_at_500(client):
    """Pagination must cap at 5 pages (500 items) to prevent infinite loops or denial of service."""
    session_jwt = create_jwt({"github_username": "huge_org_user", "github_id": 222222})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    batch = [
        {"name": f"repo-{i}", "full_name": f"huge_org/repo-{i}", "owner": {"login": "huge_org"}, "private": False, "description": "d", "language": "Go", "updated_at": "2026-09-01", "default_branch": "main"}
        for i in range(100)
    ]

    with patch("platform_app.server.routers.github_setup._get_user_token", new_callable=AsyncMock) as mock_get_token, \
         patch("httpx.AsyncClient.get", new_callable=AsyncMock) as mock_http_get:

        mock_get_token.return_value = "gho_valid_user_token"

        resp = MagicMock()
        resp.status_code = 200
        resp.json.return_value = batch
        mock_http_get.return_value = resp

        response = client.get("/api/github/user-repos")
        assert response.status_code == 200
        data = response.json()
        assert len(data) == 500  # Capped at 5 * 100
        assert mock_http_get.call_count == 5


# ==============================================================================
# 4. HEADER VS COOKIE AUTH PRECEDENCE & JWT SECURITY
# ==============================================================================

@pytest.mark.unit
def test_auth_precedence_cookie_wins_over_authorization_header(client):
    """When BOTH HttpOnly Cookie (User A) and Authorization: Bearer Header (User B) are sent,
    Cookie takes precedence (User A is authenticated)."""
    jwt_cookie_user_a = create_jwt({"github_username": "cookie_alice", "github_id": 1001})
    jwt_header_user_b = create_jwt({"github_username": "header_bob", "github_id": 1002})

    client.cookies.set(SESSION_COOKIE_NAME, jwt_cookie_user_a, domain="testserver.local", path="/")

    response = client.get(
        "/api/auth/me",
        headers={"Authorization": f"Bearer {jwt_header_user_b}"},
    )
    assert response.status_code == 200
    data = response.json()
    assert data["github_username"] == "cookie_alice"
    assert data["github_id"] == 1001


@pytest.mark.unit
def test_auth_precedence_header_fallback_when_no_cookie(client):
    """When NO Cookie is sent, Authorization: Bearer Header is used for authentication (API clients)."""
    jwt_header_user_b = create_jwt({"github_username": "header_bob", "github_id": 1002})

    response = client.get(
        "/api/auth/me",
        headers={"Authorization": f"Bearer {jwt_header_user_b}"},
    )
    assert response.status_code == 200
    data = response.json()
    assert data["github_username"] == "header_bob"
    assert data["github_id"] == 1002


@pytest.mark.unit
def test_auth_precedence_invalid_cookie_does_not_silently_fallback_to_header(client):
    """If an invalid/corrupt cookie is present, authentication MUST FAIL with 401 and not silently
    switch identity to the Authorization header."""
    jwt_header_user_b = create_jwt({"github_username": "header_bob", "github_id": 1002})

    client.cookies.set(SESSION_COOKIE_NAME, "corrupt_garbage_jwt_cookie", domain="testserver.local", path="/")

    response = client.get(
        "/api/auth/me",
        headers={"Authorization": f"Bearer {jwt_header_user_b}"},
    )
    assert response.status_code == 401
    assert response.json()["detail"] == "Invalid or expired JWT"


@pytest.mark.unit
def test_auth_malformed_authorization_headers(client):
    """Malformed Authorization headers (non-Bearer, missing token, Basic auth) must return 401."""
    # Basic auth
    r1 = client.get("/api/auth/me", headers={"Authorization": "Basic dXNlcjpwYXNz"})
    assert r1.status_code == 401

    # Bearer with empty token
    r2 = client.get("/api/auth/me", headers={"Authorization": "Bearer "})
    assert r2.status_code == 401

    # Random token prefix
    r3 = client.get("/api/auth/me", headers={"Authorization": "Token 12345"})
    assert r3.status_code == 401


@pytest.mark.unit
def test_auth_forged_jwt_secret_rejected(client):
    """JWT signed with an attacker's key must be rejected with 401 Unauthorized."""
    attacker_secret = "attacker-secret-key-that-does-not-match"
    forged_payload = {
        "github_username": "victim_admin",
        "github_id": 1,
        "exp": datetime.now(timezone.utc) + timedelta(hours=24),
    }
    forged_jwt = jwt.encode(forged_payload, attacker_secret, algorithm="HS256")

    response = client.get(
        "/api/auth/me",
        headers={"Authorization": f"Bearer {forged_jwt}"},
    )
    assert response.status_code == 401
    assert response.json()["detail"] == "Invalid or expired JWT"


@pytest.mark.unit
def test_auth_expired_jwt_rejected(client):
    """Expired JWT (exp in the past) must be rejected with 401 Unauthorized."""
    secret = os.environ.get("JWT_SECRET")
    expired_payload = {
        "github_username": "expired_user",
        "github_id": 123,
        "exp": datetime.now(timezone.utc) - timedelta(hours=1),  # 1 hour in the past
    }
    expired_jwt = jwt.encode(expired_payload, secret, algorithm="HS256")

    client.cookies.set(SESSION_COOKIE_NAME, expired_jwt, domain="testserver.local", path="/")

    response = client.get("/api/auth/me")
    assert response.status_code == 401
    assert response.json()["detail"] == "Invalid or expired JWT"


@pytest.mark.unit
def test_auth_token_not_leaked_in_auth_me(client):
    """Verify /api/auth/me leaks zero raw or encrypted token data."""
    session_jwt = create_jwt({
        "github_username": "privacy_user",
        "github_id": 999111,
        "pat": "ghp_LEAK_TEST",
        "encrypted_token": "fernet_LEAK_TEST",
    })
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    response = client.get("/api/auth/me")
    assert response.status_code == 200
    data = response.json()
    assert set(data.keys()) == {"github_username", "github_id"}
    assert "pat" not in data
    assert "token" not in data
    assert "encrypted_token" not in data


# ==============================================================================
# 5. PAT ENDPOINT FEATURE-GATING SECURITY
# ==============================================================================

@pytest.mark.unit
def test_pat_endpoint_disabled_by_default(client):
    """POST /api/github/token must return 403 Forbidden by default (when PAT_ENDPOINT_ENABLED is unset/false)."""
    session_jwt = create_jwt({"github_username": "pat_tester", "github_id": 111000})
    client.cookies.set(SESSION_COOKIE_NAME, session_jwt, domain="testserver.local", path="/")

    response = client.post(
        "/api/github/token",
        json={"token": "ghp_test_token_value_123"},
    )
    assert response.status_code == 403
    assert "PAT endpoint is not enabled" in response.json()["detail"]
